apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "intel_sriov_ngnet",
                "resourcePrefix": "intel.com",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["154c"],
                    "drivers": ["iavf"],
                    "pfNames": ["enp11s0f0"]
                }
            },
            {
                "resourceName": "intel_sriov_othernet",
                "resourcePrefix": "intel.com",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["154c"],
                    "drivers": ["iavf"],
                    "pfNames": ["enp11s0f1"]
                }
            }
        ]
    }