---
- name: 0.系统初始化
  gather_facts: false
  hosts: newnode 
  roles:
    - common
  tags: common 

- name: 1.更新newnode dns
  gather_facts: false
  hosts:
    - k8s
    - newnode
  tasks:
    - name: 更新hosts
      template: src=tools/newnode/newnode_hosts.j2 dest=/etc/hosts
      tags: update_hosts

- name: 2.部署containerd
  gather_facts: false
  hosts: newnode 
  roles:
    - containerd 
  tags: containerd

- name: 3.部署K8S Node
  gather_facts: false
  hosts: newnode
  roles:
    - node
  tags: node

- name: 4.导入离线镜像
  gather_facts: false
  hosts: newnode 
  roles:
    - images
  tags: images