---
- name: 00节点更新containerd
  gather_facts: false
  hosts: 
    - newnode
  tasks:
    - name: 创建containerd证书目录
      file: dest=/etc/containerd/certs.d/{{ HARBOR_REGISTRY }} state=directory

    - name: 分发containerd证书
      copy: src=harbor_cert/{{ item }} dest=/etc/containerd/certs.d/{{ HARBOR_REGISTRY }}
      with_items:
        - ca.pem
        - harbor.pem
        - harbor-key.pem

    - name: 重配 containerd 文件
      template: src=config.toml.j2 dest=/etc/containerd/config.toml

    - name: 重启 containerd 服务
      shell: systemctl daemon-reload && systemctl restart containerd

- name: 01更新harbor dns
  gather_facts: false
  hosts: 
    - newnode
  tasks:
    - name: /etc/hosts添加DNS
      lineinfile:
        dest: /etc/hosts
        state: present
        regexp: '{{ HARBOR_DOMAIN }}'
        line: "{{ groups['harbor'][0] }} {{ HARBOR_DOMAIN }}"
      when: " [groups.harbor[0]]['HARBOR_DOMAIN'] != ''"