---
#- name: test
#  gather_facts: false
#  hosts: harbor
#  tasks:
#    - name: test
#      debug:
#        msg:
#          - "{{ NEW_INSTALL }}"
#          - "NEW_INSTALL"
#          - "{{ groups['harbor'][0] }}"
#          - "{{ groups['harbor'] }}"
#          - "{{ groups['k8s'] }}"
#          - "{{ inventory_hostname }}"
#          - "{{ hostvars[inventory_hostname] }}"


- name: 00更新tls
  gather_facts: false
  hosts: localhost
  roles:
    - tls
  tags: harbor


- name: 01安装harbor
  gather_facts: false
  hosts: harbor
  roles:
    - docker
    - harbor
  tags: harbor

- name: 02更新harbor dns
  gather_facts: false
  hosts: 
    - harbor
  tasks:
    - name: /etc/hosts添加DNS
      lineinfile:
        dest: /etc/hosts
        state: present
        regexp: '{{ HARBOR_DOMAIN }}'
        line: "{{ groups['harbor'][0] }} {{ HARBOR_DOMAIN }}"
  tags: harbor

- name: 03 docker登录harbor
  gather_facts: false
  hosts: 
    - harbor
  tasks:
    - name: docker登录harbor
      shell: echo {{ HARBOR_PASSWORD }} | docker login -u admin --password-stdin https://{{ HARBOR_REGISTRY }}
  tags: harbor_login
  tags: harbor
#退出登录 rm -rf /root/.docker/config.json