---
#- name: test
#  gather_facts: false
#  hosts: harbor
#  tasks:
#    - name: test
#      debug:
#        msg:
#          - "{{ groups['nfs_server'] }}"
#          - "{{ inventory_hostname }}"
#          - "{{ hostvars[inventory_hostname] }}"


- name: 00安装nfs_server
  gather_facts: false
  hosts: nfs_server
  roles:
    - nfs
  tags: nfs