---
- name: 0.自签证书 
  gather_facts: false
  hosts: localhost 
  roles:
    - tls
  tags: tls

- name: 1.部署ETCD集群
  gather_facts: false
  hosts: etcd
  roles:
    - etcd
  tags: etcd

- name: 2.部署K8S Master
  gather_facts: false
  hosts: master
  roles:
    - master
  tags: master

- name: 3.部署K8S Node
  gather_facts: false
  hosts: k8s
  roles:
    - node
  tags: node

- name: 4.部署插件
  gather_facts: false
  hosts: master
  roles:
    - addons
  tags: addons