---
- name: Gather grub cmdline parameters
  command: "grep ^GRUB_CMDLINE_LINUX /etc/default/grub"
  register: grub_cmdline

- name: printf GRUB_CMDLINE_LINUX
  debug:
    msg: "{{ grub_cmdline.stdout }}"

- name: Set IOMMU parameters if not present
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=.*'
    line: 'GRUB_CMDLINE_LINUX="{{ grub_cmdline.stdout }} iommu=on iommu.passthrough=on"'
    backrefs: yes
  when: "'iommu=on' not in grub_cmdline.stdout"

- name: Update grub configuration
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: "'iommu=on' not in grub_cmdline.stdout"