apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net1
  annotations: 
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_vfnetdevice 
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-network",
  "ipam": {
    "type": "host-local",
#    "subnet": "10.56.217.0/24",
#    "rangeStart": "10.56.217.1", # 设置可分配的ip段 
#    "rangeEnd": "10.56.217.12", 
#    "routes": [{
#      "dst": "0.0.0.0/0"
#    }],
#    "gateway": "10.56.217.1"
  }
}'