apiVersion: "k8s.cni.cncf.io/v1" 
kind: NetworkAttachmentDefinition 
metadata: 
  name: sriov-net2
  annotations: k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_netdevice 
spec: 
  config: '{ 
    cniVersion": "0.3.1", 
    name": "sriov-network", 
    plugins": [ 
         { 
             "type": "sriov", 
             "ipam": { 
                 "type": "host-local", # 使用host-local作为ipam插件 
                 "subnet": "192.168.133.0/24", # 设置子网 
                 "rangeStart": "192.168.133.150", # 设置可分配的ip段 
                 "rangeEnd": "192.168.133.189", 
                 "routes": [ 
                     { "dst": "0.0.0.0/0" } 
                 ],
                 "gateway": "192.168.133.254" 
             } 
         },
         {
             "type": "sbr" #设置sbr 
         } 
     ] 
  }'