apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  restartPolicy: Never
  containers:
    - name: cuda-container
      image: ubuntu:latest
      imagePullPolicy: "IfNotPresent"
      command:
      - bash
      - -c
      args:
      - |
        nvidia-smi
        sleep 10000
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule