---
#如果需要给类型资源如 Deployment，StatefulSet 绑定子网，需要将 ovn.kubernetes.io/logical_switch Annotation 设置在 spec.template.metadata.annotations。
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rj-cu-test
  namespace: default
spec:
  selector:
    matchLabels:
      app: bbu
  replicas: 1 # 指定Pod副本数
  template:
    metadata:
      labels:
        app: bbu
# Deployment类型放此处
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
             { "name" : "sriov-net1",
               "namespace": "default",
               "interface": "enp13s0f0"
             },
             { "name" : "sriov-net1",
               "namespace": "default",
               "interface": "enp13s0f1"
             },
             { "name" : "sriov-net1",
               "namespace": "default",
               "interface": "enp1s0f1"
             }
        ]'
    spec:
      containers:
      - name: rj-cu
        image: openeuler-22.03-lts:rj3
        imagePullPolicy: IfNotPresent
        ##https://www.alibabacloud.com/help/zh/ack/ack-managed-and-ack-dedicated/user-guide/run-dpdk-applications
        command: ["/bin/sh", "-c"] 
        ##while true; do echo hello; sleep 3600000; done;
        args:
        - echo "rj-cu starting";
          mount -o remount,rw /sys/;
          /usr/sbin/init;
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /mnt/huge_1GB
          name: hugepage
        - mountPath: /dev
          name: dev
        #cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us
        #cat /sys/fs/cgroup/memory/memory.limit_in_bytes
        resources:
          requests:
            memory: 4Gi
            hugepages-1Gi: 4Gi
            cpu: 10
            intel.com/intel_sriov_vfnetdevice: '3'
          limits:
            memory: 4Gi
            hugepages-1Gi: 4Gi
            cpu: 10
            intel.com/intel_sriov_vfnetdevice: '3'
      nodeSelector:
        kubernetes.io/hostname: k8s-node1 
      volumes:
      - name: hugepage
        emptyDir:
          medium: HugePages
      - name: dev
        hostPath:
          path: /dev
          type: Directory