apiVersion: "k8s.cni.cncf.io/v1" 
kind: NetworkAttachmentDefinition 
metadata: 
  name: macvlan-net-node1-enp11s0f0
spec: 
  config: '{ 
    "cniVersion": "0.3.1", 
    "type": "macvlan", 
    "master": "enp11s0f0", 
    "mode": "bridge", 
    "ipam": { 
      "type": "host-local", 
      "subnet": "192.168.0.0/24", 
      "rangeStart": "192.168.0.200", 
      "rangeEnd": "192.168.0.216", 
      "routes": [ 
        { "dst": "0.0.0.0/0" } 
      ],
      "gateway": "192.168.0.1" 
    } 
  }'