apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tower
    app.kubernetes.io/name: tower
  name: tower
  namespace: kubesphere-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tower
      app.kubernetes.io/name: tower
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tower
        app.kubernetes.io/name: tower
    spec:
      containers:
        - command:
            - /proxy
            - --ca-cert=/ca.crt
            - --ca-key=/ca.key
            - --v=4
            - --leader-elect=true
          image: registry.zjy.com/tsz/kubesphere/tower:v0.2.0
          imagePullPolicy: IfNotPresent
          name: tower
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
      serviceAccountName: kubesphere
      affinity: {}
      nodeSelector: {}
      tolerations: []
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: tower
  name: tower
  namespace: kubesphere-system
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: tower
  sessionAffinity: None
  type: LoadBalancer