#创建 VPC 网关并配置默认路由
---
kind: VpcNatGateway
apiVersion: kubeovn.io/v1
metadata:
  name: gw1
spec:
  vpc: test-vpc-1
  subnet: net1
  lanIp: 10.0.1.254                         #vpc-nat-gateway pod ip
  qosPolicy: qos-natgw-example
  selector:
    - "kubernetes.io/hostname: k8s-node1"   #vpc-nat-gateway pod选择位置
    - "kubernetes.io/os: linux"
  externalSubnets:
    - ovn-vpc-external-network

#vpc：该 VpcNatGateway 所属的 VPC。
#subnet：为 VPC 内某个 Subnet 名，VPC 网关 Pod 会在该子网下用 lanIp 来连接租户网络。
#lanIp：subnet 内某个未被使用的 IP，VPC 网关 Pod 最终会使用该 IP。当 VPC 配置路由需要指向当前 VpcNatGateway 时 nextHopIP 需要设置为这个 lanIp。
#selector：VpcNatGateway Pod 的节点选择器，格式和 Kubernetes 中的 NodeSelector 格式相同。
#externalSubnets： VPC 网关使用的外部网络，如果不配置则默认使用 ovn-vpc-external-network，当前版本只支持配置一个外部网络。

#nat gw pod 创建之后，net1 arp 是关闭的，ping 不通物理网关，创建 eip 后会自动打开 arp，可以 ping 通。