replicaCount: 1

image:
  ks_controller_manager_repo: registry.zjy.com/tsz/kubesphere/ks-controller-manager
  ks_controller_manager_tag: v3.3.2
  ks_apiserver_repo: registry.zjy.com/tsz/kubesphere/ks-apiserver
  ks_apiserver_tag: v3.3.2
  ks_console_repo: registry.zjy.com/tsz/kubesphere/ks-console
  ks_console_tag: v3.3.2
  ks_kubectl_repo: registry.zjy.com/tsz/kubesphere/kubectl
  ks_kubectl_tag: v1.22.0
  nginx_ingress_controller_repo: registry.zjy.com/tsz/kubesphere/nginx-ingress-controller
  nginx_ingress_controller_tag: v1.1.0
  defaultbackend_repo: registry.zjy.com/tsz/mirrorgooglecontainers/defaultbackend-arm64
  defaultbackend_tag: 1.4
  bookinfo_productpage_v1_repo: registry.zjy.com/tsz/kubesphere/examples-bookinfo-productpage-v1
  bookinfo_productpage_v1_tag: 1.16.2
  bookinfo_reviews_v1_repo: registry.zjy.com/tsz/kubesphere/examples-bookinfo-reviews-v1
  bookinfo_reviews_v1_tag: 1.16.2
  bookinfo_details_v1_repo: registry.zjy.com/tsz/kubesphere/examples-bookinfo-details-v1
  bookinfo_details_v1_tag: 1.16.2
  bookinfo_ratings_v1_repo: registry.zjy.com/tsz/kubesphere/examples-bookinfo-ratings-v1
  bookinfo_ratings_v1_tag: 1.16.3
  pullPolicy: IfNotPresent

config:
  create: false

adminPassword: ""
console:
  type: NodePort
  port: 30880



kube_version: v1.24.2

apiserver:
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 100Mi

controller:
  resources:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 30m
      memory: 50Mi

nodeAffinity:
  preferredDuringSchedulingIgnoredDuringExecution:
  - weight: 100
    preference:
      matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: In
        values:
        - ""

nodeSelector: {}
tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 60
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 60
