---
- name: 导入calico镜像（需要花费一些时间...）
  shell: cd {{ tmp_dir }}/images/calico && \
         for image in $(ls *.tar*);do ctr -n=k8s.io image import $image;done

- name: 准备calico的部署文件
  copy: src=calico dest={{ tmp_dir }}
  tags: addons_delete

- name: 删除calico部署
  shell: "kubectl delete -f {{ tmp_dir }}/calico/ || echo true; sleep 3"
  tags: addons_delete

- name: 创建calico部署
  shell: "kubectl apply -f {{ tmp_dir }}/calico/"