---
- name: 创建临时目录
  copy: src=calico dest={{ tmp_dir }}
  tags:
    - addons_delete
    - addons_delete_calico

- block:
    - name: 删除旧 calico-etcd-secrets
      shell: "kubectl -n kube-system delete secrets calico-etcd-secrets || echo NotFound"
      tags:
        - addons_delete
        - addons_delete_calico

    - name: 准备calico的部署文件
      template: src=calico/{{ item }} dest={{ tmp_dir }}/calico/{{ item.split('.')[:-1]|join('.') }}
      with_items:
       - calico.yaml.j2
      tags:
        - addons_delete
        - addons_delete_calico

    - name: 删除calico部署
      shell: "kubectl delete -f {{ tmp_dir }}/calico/calico.yaml || echo true; sleep 3"
      tags:
        - addons_delete
        - addons_delete_calico

    - name: 卸载calico旧的配置
      shell: |
             rm -rf /etc/cni/net.d/10-calico.conflist
             rm -rf /etc/cni/net.d/calico-kubeconfig || echo true
             rm -rf /etc/cni/net.d/calico-tls || echo true
      delegate_to: "{{ item }}"
      with_items: "{{ groups.k8s }}"
      ignore_errors: true
      tags:
        - addons_delete
        - addons_delete_calico

    - name: 创建 calico-etcd-secrets
      shell: "kubectl create secret generic -n kube-system calico-etcd-secrets \
              --from-file=etcd-ca={{ k8s_work_dir }}/ssl/etcd/ca.pem \
              --from-file=etcd-key={{ k8s_work_dir }}/ssl/etcd/server-key.pem \
              --from-file=etcd-cert={{ k8s_work_dir }}/ssl/etcd/server.pem"

    - name: 创建calico部署
      shell: "kubectl apply -f {{ tmp_dir }}/calico/calico.yaml"

- import_tasks: calico-rr.yml
  when: 'calico_rr_enable|bool'

#loadbalancer ip暴露
#calicoctl patch BGPConfig default --patch '{"spec": {"serviceLoadBalancerIPs": [{"cidr": "10.11.0.0/16"},{"cidr":"10.1.5.0/24"}]}}'
#serviceIP暴露
#calicoctl patch BGPConfig default --patch '{"spec": {"serviceClusterIPs": [{"cidr": "10.233.0.0/18"}]}}'
#calico+cilium
#https://docs.cilium.io/en/stable/installation/cni-chaining-calico/