---
- name: 导入dns镜像（需要花费一些时间...）
  shell: cd {{ tmp_dir }}/images/dns && \
         for image in $(ls *.tar*);do ctr -n=k8s.io image import $image;done

- name: 准备DNS的部署文件
  copy: src=dns dest={{ tmp_dir }}
  tags: addons_delete

#- name: 准备DNS的部署文件
#  template: src=coredns.yaml.j2 dest={{ tmp_dir }}/coredns.yaml

- name: 删除coredns部署
  shell: "kubectl delete -f {{ tmp_dir }}/dns/ || echo true; sleep 3"
  tags: addons_delete

- name: 创建coredns部署
  shell: "kubectl apply -f {{ tmp_dir }}/dns/"