---
- name: 准备ingress的部署文件
  copy: src=ingress dest={{ tmp_dir }}
  tags:
    - addons_delete
    - addons_delete_ingress

#- name: copy ingress tool
#  shell: >
#         cd {{ tmp_dir }}/ingress&&
#         cp ingress-nginx-4.7.1.tgz {{ HELM_PATH }}/charts &&
#         helm repo index {{ HELM_PATH }}/charts --url http://{{ groups['helm'][0] }}:{{ HELM_PORT }}/charts &&
#         helm repo update 

- name: 删除ingress部署(test)
  shell: "kubectl delete -f {{ tmp_dir }}/ingress/nginx-ingress.yaml || echo true; sleep 3"
  tags:
    - addons_delete
    - addons_delete_ingress

#- name: helm 删除 ingress-nginx-4.7.1
#  shell: "helm delete ingress-nginx -n ingress-nginx || echo true; sleep 5"
#  tags:
#    - addons_delete
#    - addons_delete_ingress
#  ignore_errors: true

#- name: 更新部署
#  shell: >
#         helm upgrade --install ingress-nginx {{ tmp_dir }}/ingress/ingress-nginx-4.7.1.tgz
#         --namespace ingress-nginx

#- name: 更新metrics部署
#  shell: >
#         helm upgrade ingress-nginx {{ tmp_dir }}/ingress/ingress-nginx-4.7.1.tgz --namespace ingress-nginx
#         --set controller.metrics.enabled=true
#         --set controller.metrics.serviceMonitor.enabled=true
#         --set controller.metrics.serviceMonitor.additionalLabels.release="prometheus"#45.23.0
#此处controller.metrics.serviceMonitor.additionalLabels.release="prometheus"应与 Helm 版本的名称相匹配kube-prometheus-stack

#- name: 更新prometheus部署
#  shell: >
#         helm upgrade -n {{ prom_namespace }} -f {{ k8s_addons_dir }}/prometheus/prom-values.yaml
#         {{ tmp_dir }}/prometheus/kube-prometheus-stack-{{ prom_chart_ver }}.tgz"
#         --set prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues=false
#         --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false

- name: 创建ingress部署(test)
  shell: "kubectl apply -f {{ tmp_dir }}/ingress/nginx-ingress.yaml"