---
- name: 创建临时目录
  copy: src=ovn dest={{ tmp_dir }}
  tags:
    - addons_delete
    - addons_delete_ovn

- block:
    - name: 准备安装相关文件
      template: src=ovn/{{ item }} dest={{ tmp_dir }}/ovn/{{ item.split('.')[:-1]|join('.') }}
      with_items:
        - "install.sh.j2"
      tags:
        - addons_delete
        - addons_delete_ovn

    - name: 卸载kube-ovn网络
      shell: 'cd {{ tmp_dir }}/ovn/ && bash cleanup.sh'
      ignore_errors: true

    - name: 安装kube-ovn网络
      shell: 'cd {{ tmp_dir }}/ovn/ && \
              bash install.sh >> {{ tmp_dir }}/ovn/install-kube-ovn-`date +"%Y%m%d%H%M%S"`.log 2>&1'
  run_once: true
  ignore_errors: true


# 等待网络插件部署成功
- name: 轮询等待kube-ovn 运行，视下载镜像速度而定
  shell: "kubectl get pod -n kube-system -o wide|grep 'kube-ovn-cni'|grep ' {{ node_name }} '|awk '{print $3}'"
  register: pod_status
  until: pod_status.stdout == "Running"
  retries: 15
  delay: 8
  ignore_errors: true
  tags: force_change_certs