---
- name: 准备kuboard的部署文件
  copy: src=kuboard dest={{ tmp_dir }}


#- name: 删除kuboard部署
#  shell: "kubectl delete -f {{ tmp_dir }}/kuboard/ || echo true; sleep 3"

#- name: 创建kuboard部署
#  shell: "kubectl apply -f {{ tmp_dir }}/kuboard/"
  
#- name: 创建kuboard部署
#  ignore_errors: yes
#  shell:" sudo docker run -d --restart=unless-stopped --name=kuboard -p 80:80/tcp -p 10081:10081/tcp -e KUBOARD_ENDPOINT="http://内网IP:80" -e KUBOARD_AGENT_SERVER_TCP_PORT="10081" -v /root/kuboard-data:/data swr.cn-east-2.myhuaweicloud.com/kuboard/kuboard:v3"