---
#- name: 允许Node加入集群
#  ignore_errors: yes
#  shell: kubectl certificate approve $(kubectl get csr |awk 'NR!=1{print $1}')

#- name: 拷贝YAML文件到Master
#  copy: src={{ item }} dest={{ tmp_dir }}
#  with_items:
#    - calico
#    - dashboard
#    - dns
#    - metrics-server

#- name: 部署Calico,Dashboard,CoreDNS等插件
#  ignore_errors: yes
#  shell: |
#         cd {{ tmp_dir }}
#         for yaml in $(ls *.yaml);do kubectl apply -f $yaml;done

- name: 创建临时目录
  file: dest={{ tmp_dir }} state=directory

- name: 分发镜像（需要花费一些时间...）
  copy: src={{ software_dir }}/images dest={{ tmp_dir }}

- name: 导入base镜像（需要花费一些时间...）
  shell: cd {{ tmp_dir }}/images/base && \
         for image in $(ls *.tar*);do ctr -n=k8s.io image import $image;done

- name: 查看Pod状态
  shell: kubectl get all --all-namespaces
  register: pod_info
- debug: var=pod_info.stdout_lines

- import_tasks: coredns.yml
#  when: '"coredns" not in pod_info.stdout'

- import_tasks: calico.yml
#  when: '"calico" not in pod_info.stdout'

- import_tasks: metrics-server.yml
#  when: '"metrics-server" not in pod_info.stdout'

- import_tasks: dashboard.yml
  tags: addons_dashboard
#  when: '"dashboard" not in pod_info.stdou'

#抛弃-不好使
#- import_tasks: kuboard.yml
#  when: '"kuboard" not in pod_info.stdout'

- import_tasks: multus.yml
  when: '"macvlan" not in pod_info.stdout'

- name: 查看Pod状态
  shell: kubectl get all --all-namespaces
  register: getall
- debug: var=getall.stdout_lines

