---
#- name: 允许Node加入集群
#  ignore_errors: yes
#  shell: kubectl certificate approve $(kubectl get csr |awk 'NR!=1{print $1}')

#- name: 拷贝YAML文件到Master
#  copy: src={{ item }} dest={{ tmp_dir }}
#  with_items:
#    - calico
#    - dashboard
#    - dns
#    - metrics-server

#- name: 部署Calico,Dashboard,CoreDNS等插件
#  ignore_errors: yes
#  shell: |
#         cd {{ tmp_dir }}
#         for yaml in $(ls *.yaml);do kubectl apply -f $yaml;done

- name: 查看Pod状态
  shell: kubectl get all --all-namespaces
  register: pod_info
  tags: 
    - addons_delete
    - addons_coredns
    - addons_calico
    - addons_metrics
    - addons_dashboard
    - addons_multus
    - addons_prometheus
    - addons_nfs

- debug: var=pod_info.stdout_lines

- import_tasks: coredns.yml
  tags: addons_coredns
  when: '"coredns" not in pod_info.stdout'

- import_tasks: calico.yml
  tags: addons_calico
  when: '"calico" not in pod_info.stdout'

- import_tasks: metrics-server.yml
  tags: addons_metrics
  when: '"metrics-server" not in pod_info.stdout'

- import_tasks: dashboard.yml
  tags: addons_dashboard
  when: '"kubernetes-dashboard" not in pod_info.stdout'

#抛弃-不好使
#- import_tasks: kuboard.yml
#  when: '"kuboard" not in pod_info.stdout'

- import_tasks: multus.yml
  tags: addons_multus
#  when: '"macvlan" not in pod_info.stdout'

- import_tasks: prometheus.yml
  tags: addons_prometheus
  #when: '"prometheus" not in pod_info.stdout'
  when: 'prom_install == "yes" or "prometheus" not in pod_info.stdout'

- import_tasks: nfs.yml
  tags: addons_nfs
  when: '"nfs-client-provisioner" not in pod_info.stdout'

- name: 查看Pod状态
  shell: kubectl get all --all-namespaces
  register: getall
- debug: var=getall.stdout_lines

