---
#- name: 允许Node加入集群
#  ignore_errors: yes
#  shell: kubectl certificate approve $(kubectl get csr |awk 'NR!=1{print $1}')

#- name: 拷贝YAML文件到Master
#  copy: src={{ item }} dest={{ tmp_dir }}
#  with_items:
#    - calico
#    - dashboard
#    - dns
#    - metrics-server

#- name: 部署Calico,Dashboard,CoreDNS等插件
#  ignore_errors: yes
#  shell: |
#         cd {{ tmp_dir }}
#         for yaml in $(ls *.yaml);do kubectl apply -f $yaml;done

- name: 查看Pod状态
  shell: kubectl get all --all-namespaces
  register: pod_info
  tags: 
    - addons_delete
    - addons_coredns
    - addons_network_calico
    - addons_network_flannel
    - addons_network_ovn
    - addons_metrics
    - addons_dashboard
    - addons_multus
    - addons_prometheus
    - addons_nfs
    - addons_metallb
    - addons_ingress
    - addons_kubesphere
  ignore_errors: true

- debug: var=pod_info.stdout_lines

- import_tasks: coredns.yml
  tags: addons_coredns
#  when: '"coredns" not in pod_info.stdout'

- import_tasks: calico.yml
  tags: addons_network_calico
  when:
    - "cluster_network == 'calico'"
#    - '"calico" not in pod_info.stdout'

- import_tasks: flannel.yml
  tags: addons_network_flannel
  when:
    - "cluster_network == 'flannel'"
#    - '"flannel" not in pod_info.stdout'

- import_tasks: kubeovn.yml
  tags: addons_network_ovn
  when:
    - "cluster_network == 'kube-ovn'"

- import_tasks: multus.yml
  tags: addons_multus
  when:
    - multus_install == "yes"
#    - '"macvlan" not in pod_info.stdout'

- import_tasks: nfs.yml
  tags: addons_nfs
#  when: '"nfs-client-provisioner" not in pod_info.stdout'

- import_tasks: metallb.yml
  tags: addons_metallb
  when:
    - metallb_install == "yes"

- import_tasks: ingress.yml
  tags: addons_ingress
  when:
    - ingress_install == "yes"

- import_tasks: metrics-server.yml
  tags: addons_metrics
  when:
    - metrics_server_install == "yes" 
#    - '"metrics-server" not in pod_info.stdout'

- import_tasks: dashboard.yml
  tags: addons_dashboard
  when:
    - dashboard_install == "yes"
#    - '"kubernetes-dashboard" not in pod_info.stdout'

- import_tasks: prometheus.yml
  tags: addons_prometheus
  when:
    - prom_install == "yes"
#    - '"prometheus" not in pod_info.stdout'

- import_tasks: kubesphere.yml
  tags: addons_kubesphere
  when:
    - kubesphere_install == "yes"
#    - '"kubesphere" not in pod_info.stdout'

- name: 查看Pod状态
  shell: kubectl get all --all-namespaces
  register: getall
- debug: var=getall.stdout_lines

