---
- name: 准备metrics-server的部署文件
  copy: src=metrics-server dest={{ tmp_dir }}

- name: 删除metrics-server部署
  shell: "kubectl delete -f {{ tmp_dir }}/metrics-server/ || echo true; sleep 3"

- name: 创建metrics-server部署
  shell: "kubectl apply -f {{ tmp_dir }}/metrics-server/"