---
- name: 导入metrics-server镜像（需要花费一些时间...）
  shell: cd {{ tmp_dir }}/images/metrics && \
         for image in $(ls *.tar*);do ctr -n=k8s.io image import $image;done

- name: 准备metrics-server的部署文件
  copy: src=metrics-server dest={{ tmp_dir }}
  tags: addons_delete

- name: 删除metrics-server部署
  shell: "kubectl delete -f {{ tmp_dir }}/metrics-server/ || echo true; sleep 3"
  tags: addons_delete

- name: 创建metrics-server部署
  shell: "kubectl apply -f {{ tmp_dir }}/metrics-server/"