---
- name: 准备multus的部署文件
  copy: src=multus dest={{ tmp_dir }}
  tags:
    - addons_delete
    - addons_delete_multus

#- name: 删除macvlan部署
#  shell: "kubectl delete -f {{ tmp_dir }}/multus/macvlan-conf.yml || echo true; sleep 5"
#  tags:
#    - addons_delete
#    - addons_delete_multus

- name: 删除multus部署
  shell: "kubectl delete -f {{ tmp_dir }}/multus/multus-daemonset.yml || echo true; sleep 5"
  tags:
    - addons_delete
    - addons_delete_multus

- name: 创建multus部署
  shell: "kubectl apply -f {{ tmp_dir }}/multus/multus-daemonset.yml"

#- name: 创建macvlan部署
#  shell: "kubectl apply -f {{ tmp_dir }}/multus/macvlan-conf.yml"