- name: 准备multus-net的部署文件
  copy: src=multus-net dest={{ tmp_dir }}
  tags:
    - addons_delete
    - addons_delete_multus_net

- block:
    - name: 删除sriov-net部署
      shell: "kubectl delete -f {{ tmp_dir }}/multus-net/12-default-sriov-net1.yml || echo true; sleep 5"
      tags:
        - addons_delete
        - addons_delete_multus_net

    - name: 创建sriov-net部署
      shell: "kubectl apply -f {{ tmp_dir }}/multus-net/12-default-sriov-net1.yml || echo true; sleep 5"
  when:
    - sriov_install == "yes"