---
- name: 导入multus镜像（需要花费一些时间...）
  shell: cd {{ tmp_dir }}/images/multus && \
         for image in $(ls *.tar*);do ctr -n=k8s.io image import $image;done

- name: 准备multus的部署文件
  copy: src=multus dest={{ tmp_dir }}
  tags: addons_delete

- name: 删除macvlan部署
  shell: "kubectl delete -f {{ tmp_dir }}/macvlan-conf.yml || echo true; sleep 5"
  tags: addons_delete

- name: 删除multus部署
  shell: "kubectl delete -f {{ tmp_dir }}/multus-daemonset.yml || echo true; sleep 5"
  tags: addons_delete

- name: 创建multus部署
  shell: "kubectl apply -f {{ tmp_dir }}/multus-daemonset.yml"

- name: 创建macvlan部署
  shell: "kubectl apply -f {{ tmp_dir }}/macvlan-conf.yml"